### ISSUE TITLE
Full frame optical flow Pipeline

### ISSUE THREAD

**Issue by Sinitca-Aleksandr** [Digiratory/TrackCellWalks#1]
Подготовить полный пайплайн обработки видео методом анализа оптического потока всего содержимого в пределах маски, оцениваемого интегральным методом (Farneback / TVL)

Вспомогательные модули и блокноты размещать в папке `research`

Желательно придерживаться использования opencv в качестве библиотеки компьютерного зрения.

В рамках текущей задачи входом должно являться видео, выходом -- флуктуационная характеристика (без анализа)

**Comment by glebsolyanik** [comment]
### Changes:

The first version of pipeline video processing has been developed by analyzing the optical flow of all content within the mask, estimated by the integral method
the [`[main.py](http://main.py/)`](http://main.py/) contains an algorithm of actions.
to a file `optical_flow.py` added functions:

- `video_based_frame_generator`, `zvi_based_frame_generator`, `frame_generator` - for converting videos to frames
- `compute_optical_flow` - calculation of optical flow

to a file [`[stats.py](http://stats.py/)`](http://stats.py/) added the make_animation function, which allows you to create an animation of frame movement and save it along the specified path
